In [13]:
import cv2
import numpy as np
import random
import matplotlib.pyplot as plt

In [14]:
print(random.randint(0,9))

3


In [15]:
rows, columns = input("Enter the size of the image: ").split()
rows = int(rows)
columns = int(columns)
print(rows)
print(columns)

Enter the size of the image: 1000 600
1000
600


In [16]:
self_created_image = np.random.randint(0, 255, (columns, rows, 3))
self_created_image = self_created_image.astype(float)
print(self_created_image)
print(type(self_created_image))

[[[205.   4. 170.]
  [121.  55.  37.]
  [ 86.  31. 191.]
  ...
  [  9. 172.  66.]
  [ 50.  83. 228.]
  [108. 194. 130.]]

 [[ 68.  40. 121.]
  [ 41.  41. 133.]
  [205.  91. 212.]
  ...
  [127. 175. 132.]
  [249. 100. 252.]
  [233.  24. 216.]]

 [[ 97.  76.  19.]
  [  2.  70. 134.]
  [161.  17.  18.]
  ...
  [ 88. 184.  50.]
  [150. 212.  27.]
  [ 12.  11.  23.]]

 ...

 [[228.  69. 213.]
  [ 21. 223. 188.]
  [ 79.  67.  45.]
  ...
  [220. 133.  19.]
  [  6.  18. 189.]
  [ 25. 113. 222.]]

 [[ 67. 250. 200.]
  [170. 131. 194.]
  [ 42. 158. 178.]
  ...
  [145. 214. 241.]
  [ 99. 227. 177.]
  [ 74. 201. 134.]]

 [[ 59.  22.  50.]
  [222. 142.  12.]
  [178. 105. 226.]
  ...
  [ 43. 147. 219.]
  [ 11.  55. 204.]
  [159. 225. 223.]]]
<class 'numpy.ndarray'>


In [17]:
self_created_image.shape

(600, 1000, 3)

In [18]:
cv2.imshow("SELF CREATED IMAGE", self_created_image)
cv2.waitKey(0) == 13
cv2.destroyAllWindows()

In [19]:
cv2.imwrite("SelfCreatedImage.jpg",self_created_image)

True